Animal.create(:name => "Fido", :species => "Dog")
Animal.create(:name => "Woof", :species => "Dog")
Animal.create(:name => "Meow", :species => "Cat")
Animal.create(:name => "Ssss", :species => "Snake")
Animal.create(:name => "Who", :species => "Owl")